// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-14Ane3cDBhWuTp1_Qud_5igXzkJkDx8',
    appId: '1:31885381116:web:278e0f044daa20e986f679',
    messagingSenderId: '31885381116',
    projectId: 'sudoku-300f0',
    authDomain: 'sudoku-300f0.firebaseapp.com',
    storageBucket: 'sudoku-300f0.appspot.com',
    measurementId: 'G-42T44TX5SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-b6rPllTdERb0MpiwtxydC1AIGb4arw',
    appId: '1:31885381116:android:c82a9d19c821290786f679',
    messagingSenderId: '31885381116',
    projectId: 'sudoku-300f0',
    storageBucket: 'sudoku-300f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcC8OXbQGuROfEifZbOOmSBR6kmo5zZxA',
    appId: '1:31885381116:ios:69a946ba52c62be786f679',
    messagingSenderId: '31885381116',
    projectId: 'sudoku-300f0',
    storageBucket: 'sudoku-300f0.appspot.com',
    iosBundleId: 'com.example.sudokuAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcC8OXbQGuROfEifZbOOmSBR6kmo5zZxA',
    appId: '1:31885381116:ios:47d7a32d28fdc51386f679',
    messagingSenderId: '31885381116',
    projectId: 'sudoku-300f0',
    storageBucket: 'sudoku-300f0.appspot.com',
    iosBundleId: 'com.example.sudokuAssistant.RunnerTests',
  );
}
